routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::match(['get', 'post'], '/botman', 'BotManController@handle');
Route::get('/botman/tinker', 'BotManController@tinker');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/pay', 'PayController@index')->name('pay.index');
Route::post('/pay/complete', 'PayController@complete')->name('pay.complete');
Route::get('/pay/thankyou', 'PayController@thankyou')->name('pay.thankyou');

Route::any('/45cdfe', 'MPesaController@val')->name('mpesa.validate');
Route::any('/64cv98', 'MPesaController@con')->name('mpesa.confirm');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login.submit');

    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/home', 'AdminHomeController@index')->name('home');
        Route::resource('admins', 'AdminController', ['except' => ['show']]);
        Route::resource('owners', 'UserController', ['except' => ['create','store','edit','update']]);
        Route::resource('houses', 'HouseController');
        Route::get('houses/{id}/edituser', 'HouseController@edituser')->name('houses.edituser');
        Route::put('houses/{id}/updateuser', 'HouseController@updateuser')->name('houses.updateuser');

        Route::resource('housetypes', 'HouseTypeController');
        Route::resource('houselocations', 'HouseLocationController');

        Route::get('/payments', 'PaymentController@index')->name('payments.index');
        Route::get('/payments/{id}', 'PaymentController@show')->name('payments.show');
        Route::post('payments/{id}/archive', 'PaymentController@archive')->name('payments.archive');;
        Route::post('payments/{id}/reverse', 'PaymentController@reverse')->name('payments.reverse');;
        Route::post('payments/{id}/confirm', 'PaymentController@confirm')->name('payments.confirm');;
        Route::post('payments/{id}/transfer', 'PaymentController@transfer')->name('payments.transfer');;

        Route::resource('enquiries', 'EnquiryController', ['only' => ['index','update']]);
    });
});

app/Enquiry.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\HasUuid;

class Enquiry extends Model
{
    use HasUuid;
    public $incrementing = false;

    protected $fillable = ['email','phone','title','message'];

    public function getStateAttribute()
    {
        if($this->addressed) {
            return "Addressed";
        } else {
            return "Not Addressed";
        }
    }
}

app/House.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\HasUuid;

class House extends Model
{
    use HasUuid;
    public $incrementing = false;

    protected $fillable = ['name','cost','monthly_plan','house_type_id','house_location_id'];

    public function getTypeAttribute()
    {
        return isset($this->house_type->name) ? $this->house_type->name : "Not set";
    }

    public function getLocationAttribute()
    {
        return isset($this->house_location->name) ? $this->house_location->name : "Not set";
    }
    
    public function getAvailableAttribute()
    {
        return isset($this->user) ? "Taken" : "Available";
    }

    public function getPaidAttribute()
    {
        if (isset($this->attributes['user_id'])) {
            return $this->payments->where('user_id',$this->attributes['user_id'])->where('confirmed',true)->where('reversed',false)->sum('amount');
        } else {
            return 0.00;
        }
    }

    public function getPendingAttribute()
    {
        return $this->cost - $this->paid;
    }

    public function house_type() {
        return $this->belongsTo('App\HouseType','house_type_id');
    }

    public function house_location() {
        return $this->belongsTo('App\HouseLocation','house_location_id');
    }

    public function user() {
        return $this->belongsTo('App\User','user_id');
    }

    public function payments() {
        return $this->hasMany('App\Payment','house_id');
    }
}

resources/views/admin/owners/addhome.blade.php
@extends('layouts.admin')

resources/views/admin/owners/index.blade.php
@extends('layouts.admin')

@section('content')
    <div>
        <h3>Manage owner accounts</h3>
    </div>

    <div>
        <table class="table table-bordered datatable">
            <thead class="thead-inverse|thead-default">
                <tr>
                    <th>Name</th>
                    <th>Email-address</th>
                    <th>Phone</th>
                    <th>National ID</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($owners as $owner)
                    <tr>
                        <td>{{$owner->name}}</td>
                        <td>{{$owner->email}}</td>
                        <td>{{$owner->phone}}</td>
                        <td>{{$owner->national_id}}</td>
                        <td>
                            <div class="row">
                                <a class="btn bg-transparent" href="{{route('admin.owners.show',$owner->id)}}" title="Details">
                                    <span class="mdi mdi-account-card-details mdi-24px"></span>
                                </a>
                                <form action="{{route('admin.owners.destroy',$owner->id)}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn bg-transparent text-danger" type="submit" title="Delete">
                                        <span class="mdi mdi-delete mdi-24px"></span>
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection

@section('footer')
    @include('includes.datatables')
@endsection

resources/views/admin/owners/show.blade.php
@extends('layouts.admin')

@section('content')

    <div class="text-center">
        <h2>{{$owner->name}}</h2>
    </div>
    <div class="row text-center">
        <div class="col-sm">
            <h5>Name</h5>
            <p>{{$owner->name}}</p>
        </div>
        <div class="col-sm">
            <h5>E-mail</h5>
            <p>{{$owner->email}}</p>
        </div>
        <div class="col-sm">
            <h5>Phone</h5>
            <p>{{$owner->phone}}</p>
        </div>
        <div class="col-sm">
            <h5>National id</h5>
            <p>{{$owner->national_id}}</p>
        </div>
    </div>
    <div>
        <h3>Houses</h3>
        <table id="house-list" class="table table-bordered table-hover datatable">
            <thead class="thead-inverse|thead-default">
                <tr>
                    <th>Name</th>
                    <th>Initial Cost</th>
                    <th>Pending</th>
                    <th>Monthly plan</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($owner->houses as $house)
                        <tr>
                            <td>
                                <a href="{{route('admin.houses.show',$house->id)}}">
                                    {{$house->name}}
                                </a>
                            </td>
                            <td>{{$house->cost}}</td>
                            <td>{{$house->pending}}</td>
                            <td>{{$house->monthly_plan}}</td>
                        </tr>
                    @endforeach
                </tbody>
        </table>
    </div>

    <div>
        <h3>Payments</h3>
        <table id="payment-list" class="table table-bordered table-hover datatable">
            <thead class="thead-inverse|thead-default">
                <tr>
                    <th>House</th>
                    <th>Amount</th>
                    <th>Date</th>
                    <th>State</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($owner->payments as $payment)
                        <tr>
                            <td>
                                <a href="{{route('admin.houses.show',$payment->house->id)}}">{{$payment->house->name}}</a>
                            </td>
                            <td>{{$payment->amount}}</td>
                            <td>{{$payment->created_at}}</td>
                            <td>{{$payment->state}}</td>
                            <td>
                                <a class="btn text-info bg-transparent" href="{{route('admin.payments.show',$payment->id)}}">
                                    <span class="mdi mdi-more mdi-24px"></span>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
        </table>
    </div>
@endsection

@section('footer')
    <script>
        $(function () {  
            $('#house-list').DataTable();
            $('#payment-list').DataTable();
        });
    </script>
@endsection