routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::match(['get', 'post'], '/botman', 'BotManController@handle');
Route::get('/botman/tinker', 'BotManController@tinker');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/pay', 'PayController@index')->name('pay.index');
Route::post('/pay/complete', 'PayController@complete')->name('pay.complete');
Route::get('/pay/thankyou', 'PayController@thankyou')->name('pay.thankyou');

Route::any('/45cdfe', 'MPesaController@val')->name('mpesa.validate');
Route::any('/64cv98', 'MPesaController@con')->name('mpesa.confirm');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login.submit');

    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/home', 'AdminHomeController@index')->name('home');
        Route::resource('admins', 'AdminController', ['except' => ['show']]);
        Route::resource('owners', 'UserController', ['except' => ['create','store','edit','update']]);
        Route::resource('houses', 'HouseController');
        Route::get('houses/{id}/edituser', 'HouseController@edituser')->name('houses.edituser');
        Route::put('houses/{id}/updateuser', 'HouseController@updateuser')->name('houses.updateuser');

        Route::resource('housetypes', 'HouseTypeController');
        Route::resource('houselocations', 'HouseLocationController');

        Route::get('/payments', 'PaymentController@index')->name('payments.index');
        Route::get('/payments/{id}', 'PaymentController@show')->name('payments.show');
        Route::post('payments/{id}/archive', 'PaymentController@archive')->name('payments.archive');;
        Route::post('payments/{id}/reverse', 'PaymentController@reverse')->name('payments.reverse');;
        Route::post('payments/{id}/confirm', 'PaymentController@confirm')->name('payments.confirm');;
        Route::post('payments/{id}/transfer', 'PaymentController@transfer')->name('payments.transfer');;

        Route::resource('enquiries', 'EnquiryController', ['only' => ['index','update']]);
    });
});

resources/views/admin/admins/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="text-center">
        <h3>Add admin</h3>
        <p>
            Fields marked by (*) are mandatory
        </p>
        @if ($errors->count() > 0)
            <p class="text-danger">
                It seems there were errors in your input
            </p>  
        @endif
    </div>

    <div>
        <form action="{{route('admin.admins.store')}}" method="POST" aria-label="{{ __('Add admin') }}">
            @csrf
            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                    @if ($errors->has('name'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                <div class="col-md-6">
                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                    @if ($errors->has('email'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone') }}</label>

                <div class="col-md-6">
                    <input id="phone" type="tel" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" name="phone" value="{{ old('phone') }}" required>

                    @if ($errors->has('phone'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('phone') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="national_id" class="col-md-4 col-form-label text-md-right">{{ __('National ID Number') }}</label>

                <div class="col-md-6">
                    <input id="national_id" type="text" class="form-control{{ $errors->has('national_id') ? ' is-invalid' : '' }}" name="national_id" value="{{ old('national_id') }}" required>

                    @if ($errors->has('national_id'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('national_id') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                <div class="col-md-6">
                    <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                    @if ($errors->has('password'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('password') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                <div class="col-md-6">
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                </div>
            </div>

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        {{ __('Add admin account') }}
                    </button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/admins/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="text-center">
        <h3>Edit {{$admin->name}}</h3>
        <p>
            Fields marked by (*) are mandatory
        </p>
        @if ($errors->count() > 0)
            <p class="text-danger">
                It seems there were errors in your input
            </p>  
        @endif
    </div>

    <div>
        <form action="{{route('admin.admins.update', $admin->id)}}" method="POST" aria-label="{{ __('Add admin') }}">
            @csrf
            @method('PUT')

            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $admin->name) }}" required autofocus>

                    @if ($errors->has('name'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                <div class="col-md-6">
                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email',$admin->email) }}" required>

                    @if ($errors->has('email'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone') }}</label>

                <div class="col-md-6">
                    <input id="phone" type="tel" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" name="phone" value="{{ old('phone', $admin->phone) }}" required>

                    @if ($errors->has('phone'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('phone') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="national_id" class="col-md-4 col-form-label text-md-right">{{ __('National ID Number') }}</label>

                <div class="col-md-6">
                    <input id="national_id" type="text" class="form-control{{ $errors->has('national_id') ? ' is-invalid' : '' }}" name="national_id" value="{{ old('national_id', $admin->national_id) }}" required>

                    @if ($errors->has('national_id'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('national_id') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        {{ __('Update details') }}
                    </button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/admins/index.blade.php
@extends('layouts.admin')

@section('content')
    <div>
        <h3>Manage admin accounts</h3>
    </div>

    <div>
        <table class="table table-bordered datatable">
            <thead class="thead-inverse|thead-default">
                <tr>
                    <th>Name</th>
                    <th>Email-address</th>
                    <th>Phone</th>
                    <th>National ID</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($admins as $admin)
                    <tr>
                        <td>{{$admin->name}}</td>
                        <td>{{$admin->email}}</td>
                        <td>{{$admin->phone}}</td>
                        <td>{{$admin->national_id}}</td>
                        <td>
                            <div class="row">
                                <a class="btn bg-transparent" href="{{route('admin.admins.edit',$admin->id)}}" title="Edit">
                                    <span class="mdi mdi-pencil mdi-24px"></span>
                                </a>
                                <form action="{{route('admin.admins.destroy',$admin->id)}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn bg-transparent text-danger" type="submit" title="Delete">
                                        <span class="mdi mdi-delete mdi-24px"></span>
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div>
        <a class="btn btn-primary" href="{{route('admin.admins.create')}}" title="Edit">
            <span class="mdi mdi-plus mdi-18px"></span> Add admin
        </a>
    </div>
@endsection

@section('footer')
    @include('includes.datatables')
@endsection